fieldLayouts:
  b7a90d55-512c-4ea5-a4d2-9d51b5024707:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f9f0f3d-8422-4982-acfa-1873b0adfcca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 483ec9e4-e5f3-4253-b0f9-249c1cb98723 # Jobs image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b870a02-8e39-47ed-bd6d-c4bf6284333e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9b9eacc5-d443-4e2e-9b8b-e732b45c258d
        userCondition: null
handle: jobsListing
hasTitleField: false
name: 'jobs listing'
section: 310b96af-04fe-4d60-b9bd-610396b332de # jobs listing
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
