fieldLayouts:
  84b5766d-2e7a-4d8d-9867-f8cc13e9dade:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3355e288-57fd-4d97-8942-ea66f91ae811
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7a4fb12f-e7ca-4de7-82a9-029b4e1edf6a # photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58312af0-c377-4982-aaa5-d0767c962c0d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb7fbe85-32b8-474d-8d65-8510bce3dfb8 # description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b107c094-7c8e-41df-8da2-54c0105302ed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b799a2bd-bb08-4af0-b2b0-56d3123643ff
        userCondition: null
handle: projects
hasTitleField: true
name: Projects
section: f541a3bc-9d47-4b06-9dc7-3cbf40f303fa # Projects
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
