columnSuffix: pkqdmklw
contentColumnType: string(400)
fieldGroup: 1d62d6ba-4632-45fa-9884-8bb7642b10d6 # Common
handle: footerCopyright
instructions: null
name: 'footer copyright'
searchable: false
settings:
  byteLimit: null
  charLimit: 100
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
