columnSuffix: null
contentColumnType: string
fieldGroup: e426384d-3ba3-4ee6-aed6-7b443dbfb7ee # jobs page
handle: jobsImage
instructions: 'add an image'
name: 'Jobs image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:5bff15a5-1f98-4a84-8ce5-0f4cc35d6d40' # Assets
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:5bff15a5-1f98-4a84-8ce5-0f4cc35d6d40' # Assets
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:5bff15a5-1f98-4a84-8ce5-0f4cc35d6d40' # Assets
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
