columnSuffix: thwxtqle
contentColumnType: text
fieldGroup: 0cb86248-587f-4d81-b636-3a3ba472901f # Home page
handle: team
instructions: 'Team members of the agency'
name: Team
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
