columnSuffix: null
contentColumnType: string
fieldGroup: 0cb86248-587f-4d81-b636-3a3ba472901f # Home page
handle: teamMembers
instructions: null
name: 'team members'
searchable: false
settings:
  contentTable: '{{%matrixcontent_teammembers}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
