defaultPlacement: end
enableVersioning: true
handle: projectListing
name: 'project listing'
propagationMethod: all
siteSettings:
  06f6444a-ae0e-4eec-9b60-be414cf4c030: # Agency
    enabledByDefault: true
    hasUrls: true
    template: _/pages/projects/index.twig
    uriFormat: projects
type: single
